# Generated by Django 4.0.6 on 2023-07-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_card_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
