# Generated by Django 4.0.6 on 2023-07-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_card_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
