# Generated by Django 4.0.6 on 2023-07-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_card_card_name_alter_card_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
