# Generated by Django 4.0.6 on 2023-07-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='Total_amount',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
