# Generated by Django 4.1.7 on 2023-08-23 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_uploadedfiles_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFiles',
        ),
    ]
