# Generated by Django 4.0.6 on 2023-07-10 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=200)),
                ('prefered_name', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=6)),
                ('country_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponAndPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('couponcode', models.CharField(max_length=255)),
                ('account_type', models.JSONField(max_length=255)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('couponfor', models.IntegerField()),
                ('number_of_user', models.IntegerField()),
                ('user_type', models.BooleanField()),
                ('discount_type', models.BooleanField()),
                ('discount', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon', models.ImageField(upload_to='HomeCardIcon')),
                ('Card_Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Card_body', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeCardTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Subtitle', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages_name', models.CharField(max_length=255, unique=True)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PetMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pet_Image', models.ImageField(upload_to='Pet_Image')),
                ('Pet_Name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserType', models.IntegerField()),
                ('Name', models.CharField(max_length=255)),
                ('plan_type', models.CharField(max_length=255)),
                ('monthly_price', models.IntegerField()),
                ('yearly_price', models.IntegerField()),
                ('discounttype', models.BooleanField()),
                ('discount', models.CharField(max_length=30)),
                ('discountmininumseat', models.IntegerField()),
                ('subscriptionservices', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_listing', models.IntegerField(blank=True, null=True)),
                ('propertype', models.JSONField(blank=True, null=True)),
                ('properlisting', models.JSONField(blank=True, null=True)),
                ('titles', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlanServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserType', models.IntegerField()),
                ('Name', models.CharField(max_length=255)),
                ('plan_type', models.CharField(max_length=255)),
                ('monthly_price', models.IntegerField()),
                ('yearly_price', models.IntegerField()),
                ('discounttype', models.BooleanField()),
                ('discount', models.CharField(max_length=30)),
                ('discountmininumseat', models.IntegerField()),
                ('subscriptionservices', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('total_listing', models.IntegerField(blank=True, null=True)),
                ('propertype', models.JSONField(blank=True, null=True)),
                ('properlisting', models.JSONField(blank=True, null=True)),
                ('listing_type', models.IntegerField(blank=True, null=True)),
                ('titles', models.TextField(blank=True, null=True)),
                ('Subscription_services', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('usertype', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCodeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zipcode', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('area_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.areamaster')),
            ],
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('country_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.countrymaster')),
            ],
        ),
        migrations.CreateModel(
            name='CityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('city_image', models.ImageField(blank=True, null=True, upload_to='City')),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('state_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.statemaster')),
            ],
        ),
        migrations.AddField(
            model_name='areamaster',
            name='city_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.citymaster'),
        ),
    ]
