# Generated by Django 4.0.6 on 2023-07-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locationexcelfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel', models.FileField(blank=True, null=True, upload_to='location_excel')),
            ],
        ),
        migrations.CreateModel(
            name='Propetyexcelfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel', models.FileField(blank=True, null=True, upload_to='property_excel')),
            ],
        ),
    ]
