# Generated by Django 4.0.6 on 2023-07-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_locationexcelfile_propetyexcelfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languageexcelfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel', models.FileField(blank=True, null=True, upload_to='language_excel')),
            ],
        ),
    ]
