# Generated by Django 4.0.6 on 2023-07-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactNow',
        ),
    ]
