# Generated by Django 4.0.6 on 2023-07-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_delete_contactnow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
