# Generated by Django 4.0.6 on 2023-07-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_delete_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenHouseProperty',
        ),
    ]
