# Generated by Django 4.0.6 on 2023-07-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_property_detail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_detail',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
