# Generated by Django 4.0.6 on 2023-07-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_property_detail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_detail',
            name='BuyerAgency',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='property_detail',
            name='SellerAgency',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='property_detail',
            name='fees',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='property_detail',
            name='property_offer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='property_detail',
            name='property_terms',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
