# Generated by Django 4.0.6 on 2023-07-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_property_detail_buyeragency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities_master',
            name='amenities_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='filter_save_serach',
            name='Annual_Taxes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='filter_save_serach',
            name='Assessment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='filter_save_serach',
            name='Available_Air_Rights',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='filter_save_serach',
            name='Bathrooms',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='filter_save_serach',
            name='Bedrooms',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='filter_save_serach',
            name='Zone',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='filter_save_serach',
            name='block',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='filter_save_serach',
            name='building_diamensions',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='filter_save_serach',
            name='far',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='filter_save_serach',
            name='filterName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='filter_save_serach',
            name='lot',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='filter_save_serach',
            name='lot_diamensions',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='filter_save_serach',
            name='room',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='filter_save_serach',
            name='stories',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='filter_save_serach',
            name='units',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='first_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='last_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='license',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='property_amenities',
            name='amenities_value',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='property_detail',
            name='Apt',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property_detail',
            name='BuyerAgency',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property_detail',
            name='SellerAgency',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property_detail',
            name='fees',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property_detail',
            name='property_offer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property_detail',
            name='property_terms',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property_detail',
            name='property_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property_detail',
            name='property_zip',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property_image',
            name='property_image_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property_listing_type',
            name='listing_position',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='property_listing_type',
            name='listing_type',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='property_listing_type',
            name='user_listing_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property_main_category',
            name='Main_category',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='property_space_availability',
            name='rate',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property_space_availability',
            name='size',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property_space_availability',
            name='space',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property_space_availability',
            name='term',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property_space_availability',
            name='type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='property_sub_category',
            name='property_sub_category_Name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='property_type',
            name='proprty_type_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='propertylisting_type',
            name='property_listing_name',
            field=models.CharField(max_length=300),
        ),
    ]
