# Generated by Django 4.1.7 on 2023-08-23 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='file',
            new_name='documents',
        ),
    ]
