# Generated by Django 4.1.7 on 2023-08-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_rename_file_documents_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='order',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
