# Generated by Django 4.1.7 on 2023-08-23 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_alter_documents_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='order',
        ),
    ]
