# Generated by Django 4.1.7 on 2023-08-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_rename_documents_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='shared',
        ),
        migrations.RemoveField(
            model_name='document',
            name='signed',
        ),
    ]
