# Generated by Django 4.1.7 on 2023-08-24 19:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_rename_document_document_file_document_share_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='share_with',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
