# Generated by Django 4.1.7 on 2023-08-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_document_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signed_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
