# Generated by Django 4.1.7 on 2023-09-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_document_signed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
