# Generated by Django 4.1.7 on 2023-09-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_document_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
