# Generated by Django 4.1.7 on 2023-09-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0029_document_share_to_alter_document_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='share_to',
            new_name='share_from',
        ),
    ]
