# Generated by Django 4.1.7 on 2023-09-06 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0030_rename_share_to_document_share_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='signed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
