# Generated by Django 4.0.6 on 2023-07-10 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertismentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Business_Phone', models.CharField(blank=True, max_length=100, null=True)),
                ('Business_Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('Industry', models.CharField(blank=True, max_length=256, null=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('last_login', models.DateField(blank=True, null=True)),
                ('AdvertismentUser_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='AdvertismentImage')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('advertisment_start_date', models.DateField(blank=True, null=True)),
                ('advertisment_end_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(blank=True, default=False, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('is_approved_date', models.DateField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(blank=True, default=False, null=True)),
                ('AdvertismentUser_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisement.advertismentuser')),
            ],
        ),
    ]
