# Generated by Django 4.0.6 on 2023-07-10 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_office_name', models.CharField(blank=True, max_length=256, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('userprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualOfficeTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_status', models.BooleanField(blank=True, null=True)),
                ('is_request', models.BooleanField(blank=True, default=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(default=secrets.token_hex, max_length=64)),
                ('virtualid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_office.virtualoffice')),
            ],
        ),
        migrations.CreateModel(
            name='customer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact_no_1', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_no_2', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('towns_of_interest', models.CharField(blank=True, max_length=256, null=True)),
                ('date_of_close', models.DateField(blank=True, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('purchase_rental_price', models.CharField(blank=True, max_length=30, null=True)),
                ('doc1', models.FileField(blank=True, null=True, upload_to='cunstomer_doc_1')),
                ('doc2', models.FileField(blank=True, null=True, upload_to='cunstomer_doc_2')),
                ('doc3', models.FileField(blank=True, null=True, upload_to='cunstomer_doc_3')),
                ('add_note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
