# Generated by Django 4.0.6 on 2023-07-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0002_virtualofficeteam_member_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VirtualOfficeTeam',
        ),
    ]
