# Generated by Django 4.0.6 on 2023-07-27 06:16

from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0003_delete_virtualofficeteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualOfficeTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_status', models.BooleanField(blank=True, null=True)),
                ('is_request', models.BooleanField(blank=True, default=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(default=secrets.token_hex, max_length=64)),
                ('member_type', models.CharField(blank=True, max_length=300, null=True)),
                ('virtualid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_office.virtualoffice')),
            ],
        ),
    ]
