# Generated by Django 4.0.6 on 2023-07-28 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0004_virtualofficeteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signed_Documnets_Custom_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(blank=True, null=True, upload_to='cunstomer_doc')),
                ('customobj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtual_office.customer_info')),
            ],
        ),
    ]
