# Generated by Django 4.0.6 on 2023-08-04 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0006_alter_customer_info_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteonvirtualofficeproperty',
            name='virtual_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtual_office.virtualoffice'),
        ),
    ]
