# Generated by Django 4.0.6 on 2023-08-07 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_agentapprovedsubscriptionplan_plan_choices_and_more'),
        ('virtual_office', '0007_noteonvirtualofficeproperty_virtual_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualofficeproperty',
            name='is_dislike',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualofficeproperty',
            name='is_like',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualofficeproperty',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualofficeproperty',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile'),
        ),
        migrations.DeleteModel(
            name='NoteOnVirtualOfficeProperty',
        ),
    ]
