# Generated by Django 4.1.7 on 2023-08-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0008_virtualofficeproperty_is_dislike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualofficeproperty',
            name='is_show',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
