# Generated by Django 4.1.7 on 2023-08-22 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virtual_office', '0009_virtualofficeproperty_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_info',
            name='originuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer_info',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_office.virtualofficeteam'),
        ),
        migrations.AlterField(
            model_name='virtualofficeteam',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
