# Generated by Django 4.1.7 on 2023-08-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0010_customer_info_originuser_alter_customer_info_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_info',
            old_name='originuser',
            new_name='origin_user',
        ),
    ]
