# Generated by Django 4.1.7 on 2023-08-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0011_rename_originuser_customer_info_origin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signed_documnets_custom_info',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/signed_documents/%Y/%m/%d'),
        ),
    ]
