# Generated by Django 4.1.7 on 2023-08-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0013_alter_signed_documnets_custom_info_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_info',
            name='doc1',
        ),
        migrations.RemoveField(
            model_name='customer_info',
            name='doc2',
        ),
        migrations.RemoveField(
            model_name='customer_info',
            name='doc3',
        ),
    ]
