# Generated by Django 4.1.7 on 2023-08-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0014_remove_customer_info_doc1_remove_customer_info_doc2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signed_documnets_custom_info',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/signed_documents'),
        ),
    ]
