# Generated by Django 4.1.7 on 2023-08-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0016_customer_info_doc1_customer_info_doc2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_info',
            name='origin_user',
        ),
        migrations.AddField(
            model_name='customer_info',
            name='origin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
