# Generated by Django 4.1.7 on 2023-08-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0018_alter_customer_info_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_info',
            name='martial_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer_info',
            name='relationship',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
