# Generated by Django 4.1.7 on 2023-08-23 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0020_rename_customobj_signed_documnets_custom_info_virtualprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signed_documnets_custom_info',
            name='virtualprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtual_office.virtualofficeteam'),
        ),
    ]
