# Generated by Django 4.1.7 on 2023-08-23 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0021_alter_signed_documnets_custom_info_virtualprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='signed_documnets_custom_info',
            name='customobj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtual_office.customer_info'),
        ),
    ]
