# Generated by Django 4.1.7 on 2023-08-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0022_signed_documnets_custom_info_customobj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signed_documnets_custom_info',
            old_name='virtualprofile',
            new_name='virtualteam',
        ),
    ]
