# Generated by Django 4.1.7 on 2023-08-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0023_rename_virtualprofile_signed_documnets_custom_info_virtualteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='signed_documnets_custom_info',
            name='shared',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='signed_documnets_custom_info',
            name='signed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='signed_documnets_custom_info',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/documents'),
        ),
    ]
