# Generated by Django 4.1.7 on 2023-08-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0024_signed_documnets_custom_info_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signed_documnets_custom_info',
            name='filename',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='signed_documnets_custom_info',
            name='shared',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
