# Generated by Django 4.1.7 on 2023-08-23 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0025_signed_documnets_custom_info_filename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signed_documnets_custom_info',
            name='virtualteam',
        ),
        migrations.AddField(
            model_name='signed_documnets_custom_info',
            name='virtualoffice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtual_office.virtualoffice'),
        ),
    ]
