# Generated by Django 4.1.7 on 2023-08-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0026_remove_signed_documnets_custom_info_virtualteam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualofficeproperty',
            name='is_show',
        ),
        migrations.AddField(
            model_name='customer_info',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
