# Generated by Django 4.1.7 on 2023-08-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0027_remove_virtualofficeproperty_is_show_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_info',
            name='profile_image',
        ),
    ]
