# Generated by Django 4.1.7 on 2023-08-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_office', '0028_remove_customer_info_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_info',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
    ]
