# Generated by Django 4.0.6 on 2023-07-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boostmarketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boostmarketingtable',
            name='CampaignName',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='boostmarketingtable',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='boostmarkitingplan',
            name='cost',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='boostmarkitingplan',
            name='impression',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
