# Generated by Django 4.0.6 on 2023-08-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boostmarketing', '0002_alter_boostmarketingtable_campaignname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.IntegerField(blank=True, null=True)),
                ('top_description', models.TextField(blank=True, null=True)),
                ('termsandservices', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='boostmarkitingplan',
            name='termsandservices',
        ),
    ]
